### ISSUE TITLE
Split StateMachineService into Service and Internal Interface

### ISSUE THREAD

**Issue by abalfour** [psibr/REstate#8]
### Prerequisites

* [x] Checked that your issue isn't already filed.

### Description

In #7 changes were made to support testing by making private static methods public virtual for Moq. Let's move these methods to an internal interface to better support test scenarios and single responsibility.

### Versions

REstate 3.0.0
REstate.Remote 3.0.0

### Additional Information

Initial request:
![image](https://user-images.githubusercontent.com/6539960/34159984-0f0ef878-e480-11e7-9b6a-84e949a323d3.png)

**Comment by aidapsibr** [comment]
MagicOnion constructs the type, constructor injection isn't feasible, and property injection is a scourge.

Options:
- `internal static class` to hold the methods
- `internal class` constructed in the `StateMachineService` as a default value on property with an internal setter.

I lean toward the latter personally since it could also have an interface which may help some tests by manually providing a mock to the `StateMachineService`.

**Comment by aidapsibr** [comment]
@abalfour I'd like to bump the priority on this since we have seen some issues with Moq not binding mocks as expected, moving to an interface would make it way easier to know when issues occur.
